language: php

php:
  - '5.5'

env:
  global:
    - RUN_UNIT_TESTS="no"

script:
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then phpunit --configuration travisci-phpunit.xml; fi

deploy:
  provider: releases
  api_key: "0c3354f7c3a4e98620f06408ceaad64aece27cdb"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true