language: php

php:
  - '5.5'

env:
  global:
    - RUN_UNIT_TESTS="no"

script:
  - if [[ $RUN_UNIT_TESTS == "yes" ]]; then phpunit --configuration travisci-phpunit.xml; fi

deploy:
  provider: releases
  api_key: "1090e00be94a6e391c6f677beba308acb6c2467e"
  skip_cleanup: true
  overwrite: true
  on:
    tags: true